### PR TITLE
[elastic] Apply dependence management into `DidChangeWorkspaceFolders`.

### PR DESCRIPTION
**Pull request by movie-travel-code**
Given that go language server has implemented the
`DidChangeWorkspaceFolders` API, language server should explore the
workspace folders to give whole pictures of them when receiving did
change workspace folders request. Once the language server gets the
whole picture, we can convert the folder into the shape that go language
server can manage the dependency for us, like deps downloading.

### CODE REVIEW

**Comment by movie-travel-code** [comment]
Visit https://github.com/elastic/code/issues/1338 for the context of the go language server dependency management.

**Comment by movie-travel-code** [comment]
> I assume there will still be an intializing call, and we might also want to support that case?

Do you mean the `initialize` request handler? `initialize` handler still need to call the `ManageDeps()`.

**Comment by movie-travel-code** [comment]
@spacedragon Given that we jump to repository **A** from repository **B**, code plugin will send `didChangeWorkspaceFolders` request. If we jump back to repository B from repository **A**, does code plugin send `didChangeWorkspaceFolders` again?

**Comment by spacedragon** [comment]
> @spacedragon Given that we jump to repository **A** from repository **B**, code plugin will send `didChangeWorkspaceFolders` request. If we jump back to repository B from repository **A**, does code plugin send `didChangeWorkspaceFolders` again?

No.
Actually, `didChangeWorkspaceFolders` is sent because B is not open and editor want open it

**Comment by movie-travel-code** [comment]
Oh, I see, the code server maintains an opened repository sets and only send `didChangeWorkspaceFolders` request if we jump to an unopened repository or delete an opened repository.

**Comment by zfy0701** [comment]
> > I assume there will still be an intializing call, and we might also want to support that case?
> 
> Do you mean the `initialize` request handler? `initialize` handler still need to call `ManageDeps()`.

right, but could you point out where the initialze request handler calls manageDeps?

**Pull request merged**
